### ISSUE TITLE
No SSL validation

### ISSUE THREAD

**Issue by andriej** [ProtoThis/python-synology#48]
As suggested in: https://github.com/home-assistant/core/issues/34888 

Library right now, even when 'verify SSL' is checked while integrating in HA, doesn't do SSL validation.
It connects even when URL provided is not matched with SSL on DSM, example:
it can connect to https://ip:5001 while domain cert (valid lets encrypt) is https://domain.name:5001.

Browser (Chrome, Firefox) throw an exception in such situation even more - HTSTS mechanisms woudln't allow to connect.
It would be nice to validate SSL and have exception thrown while validation and further while normal operation, because some people may want to integrate external DSM systems, available remotely through Internet.

**Comment by mib1185** [comment]
ssl_validation on this module will be available with #76 , but also change on home assistant synology-dsm integration is needed, to pass parameter ``ssl_validaion'' to python-synology modul (_for now only choise to use ssl is present, but not to validate ssl_)
