### ISSUE TITLE
Requirement is pinned for python-synology 0.8.2: urllib3>=1.24.3,<1.25

### ISSUE THREAD

**Issue by MartinHjelmare** [ProtoThis/python-synology#63]
- This library supports an integration in Home Assistant.
- The upcoming pip resolver will be more strict in resolving package version conflicts:
http://pyfound.blogspot.com/2020/03/new-pip-resolver-to-roll-out-this-year.html#what-will-change
- To avoid future issues it would be good if this library would change its pinning to allow any higher version and just set a minimum version.

Thanks for your support of Home Assistant!

**Comment by onkelbeh** [comment]
Yes, this is disrupting al lot of dependencies.
Please get rid of the `urllib3<1.25 `req.

**Comment by onkelbeh** [comment]
Hi,

hope you don't mind that I use your component in [Home Assistant Gentoo Overlay](https://github.com/onkelbeh/HomeAssistantRepository).

Component: https://github.com/onkelbeh/HomeAssistantRepository/tree/master/dev-python/python-synology

I do not use this component myself, but I know that a couple of users do. I have confirmation that it is working with `urllib3-1.25.10`.

For now, I added a small patch to the Ebuild:

```bash
src_prepare() {
    sed -e 's;urllib3>=1.24.3,<1.25;urllib3>=1.24.3;' \
        -i requirements.txt || die
    eapply_user
}
```

Thanks a lot.
