### ISSUE TITLE
TypeError: __init__() missing 2 required positional arguments: 'api' and 'code'

### ISSUE THREAD

**Issue by Nitesedge** [ProtoThis/python-synology#64]
Just installed v0.8.2 and receiving: TypeError: __init__() missing 2 required positional arguments: 'api' and 'code'

#### Install
(venv) root@beaglebone:~/python-synology# python setup.py install
running install
running bdist_egg
running egg_info
writing top-level names to python_synology.egg-info/top_level.txt
writing requirements to python_synology.egg-info/requires.txt
writing python_synology.egg-info/PKG-INFO
writing dependency_links to python_synology.egg-info/dependency_links.txt
reading manifest file 'python_synology.egg-info/SOURCES.txt'
writing manifest file 'python_synology.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-armv7l/egg
running install_lib
running build_py
creating build/bdist.linux-armv7l/egg
creating build/bdist.linux-armv7l/egg/synology_dsm
copying build/lib/synology_dsm/synology_dsm.py -> build/bdist.linux-armv7l/egg/synology_dsm
copying build/lib/synology_dsm/helpers.py -> build/bdist.linux-armv7l/egg/synology_dsm
copying build/lib/synology_dsm/exceptions.py -> build/bdist.linux-armv7l/egg/synology_dsm
copying build/lib/synology_dsm/const.py -> build/bdist.linux-armv7l/egg/synology_dsm
copying build/lib/synology_dsm/__init__.py -> build/bdist.linux-armv7l/egg/synology_dsm
creating build/bdist.linux-armv7l/egg/synology_dsm/api
creating build/bdist.linux-armv7l/egg/synology_dsm/api/dsm
copying build/lib/synology_dsm/api/dsm/network.py -> build/bdist.linux-armv7l/egg/synology_dsm/api/dsm
copying build/lib/synology_dsm/api/dsm/information.py -> build/bdist.linux-armv7l/egg/synology_dsm/api/dsm
copying build/lib/synology_dsm/api/dsm/__init__.py -> build/bdist.linux-armv7l/egg/synology_dsm/api/dsm
creating build/bdist.linux-armv7l/egg/synology_dsm/api/storage
copying build/lib/synology_dsm/api/storage/storage.py -> build/bdist.linux-armv7l/egg/synology_dsm/api/storage
copying build/lib/synology_dsm/api/storage/__init__.py -> build/bdist.linux-armv7l/egg/synology_dsm/api/storage
copying build/lib/synology_dsm/api/__init__.py -> build/bdist.linux-armv7l/egg/synology_dsm/api
creating build/bdist.linux-armv7l/egg/synology_dsm/api/core
copying build/lib/synology_dsm/api/core/security.py -> build/bdist.linux-armv7l/egg/synology_dsm/api/core
copying build/lib/synology_dsm/api/core/__init__.py -> build/bdist.linux-armv7l/egg/synology_dsm/api/core
copying build/lib/synology_dsm/api/core/share.py -> build/bdist.linux-armv7l/egg/synology_dsm/api/core
copying build/lib/synology_dsm/api/core/utilization.py -> build/bdist.linux-armv7l/egg/synology_dsm/api/core
creating build/bdist.linux-armv7l/egg/synology_dsm/api/surveillance_station
copying build/lib/synology_dsm/api/surveillance_station/const.py -> build/bdist.linux-armv7l/egg/synology_dsm/api/surveillance_station
copying build/lib/synology_dsm/api/surveillance_station/camera.py -> build/bdist.linux-armv7l/egg/synology_dsm/api/surveillance_station
copying build/lib/synology_dsm/api/surveillance_station/__init__.py -> build/bdist.linux-armv7l/egg/synology_dsm/api/surveillance_station
byte-compiling build/bdist.linux-armv7l/egg/synology_dsm/synology_dsm.py to synology_dsm.cpython-35.pyc
byte-compiling build/bdist.linux-armv7l/egg/synology_dsm/helpers.py to helpers.cpython-35.pyc
byte-compiling build/bdist.linux-armv7l/egg/synology_dsm/exceptions.py to exceptions.cpython-35.pyc
byte-compiling build/bdist.linux-armv7l/egg/synology_dsm/const.py to const.cpython-35.pyc
byte-compiling build/bdist.linux-armv7l/egg/synology_dsm/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-armv7l/egg/synology_dsm/api/dsm/network.py to network.cpython-35.pyc
byte-compiling build/bdist.linux-armv7l/egg/synology_dsm/api/dsm/information.py to information.cpython-35.pyc
byte-compiling build/bdist.linux-armv7l/egg/synology_dsm/api/dsm/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-armv7l/egg/synology_dsm/api/storage/storage.py to storage.cpython-35.pyc
byte-compiling build/bdist.linux-armv7l/egg/synology_dsm/api/storage/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-armv7l/egg/synology_dsm/api/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-armv7l/egg/synology_dsm/api/core/security.py to security.cpython-35.pyc
byte-compiling build/bdist.linux-armv7l/egg/synology_dsm/api/core/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-armv7l/egg/synology_dsm/api/core/share.py to share.cpython-35.pyc
byte-compiling build/bdist.linux-armv7l/egg/synology_dsm/api/core/utilization.py to utilization.cpython-35.pyc
byte-compiling build/bdist.linux-armv7l/egg/synology_dsm/api/surveillance_station/const.py to const.cpython-35.pyc
byte-compiling build/bdist.linux-armv7l/egg/synology_dsm/api/surveillance_station/camera.py to camera.cpython-35.pyc
byte-compiling build/bdist.linux-armv7l/egg/synology_dsm/api/surveillance_station/__init__.py to __init__.cpython-35.pyc
creating build/bdist.linux-armv7l/egg/EGG-INFO
copying python_synology.egg-info/PKG-INFO -> build/bdist.linux-armv7l/egg/EGG-INFO
copying python_synology.egg-info/SOURCES.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying python_synology.egg-info/dependency_links.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying python_synology.egg-info/requires.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying python_synology.egg-info/top_level.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/python_synology-0.8.2-py3.5.egg' and adding 'build/bdist.linux-armv7l/egg' to it
removing 'build/bdist.linux-armv7l/egg' (and everything under it)
Processing python_synology-0.8.2-py3.5.egg
Copying python_synology-0.8.2-py3.5.egg to /root/venv/lib/python3.5/site-packages
Adding python-synology 0.8.2 to easy-install.pth file

Installed /root/venv/lib/python3.5/site-packages/python_synology-0.8.2-py3.5.egg
Processing dependencies for python-synology==0.8.2
Searching for simplejson==3.17.2
Best match: simplejson 3.17.2
Adding simplejson 3.17.2 to easy-install.pth file

Using /root/venv/lib/python3.5/site-packages
Searching for future==0.18.2
Best match: future 0.18.2
Adding future 0.18.2 to easy-install.pth file
Installing pasteurize script to /root/venv/bin
Installing futurize script to /root/venv/bin

Using /root/venv/lib/python3.5/site-packages
Searching for six==1.15.0
Best match: six 1.15.0
Adding six 1.15.0 to easy-install.pth file

Using /root/venv/lib/python3.5/site-packages
Searching for urllib3==1.24.3
Best match: urllib3 1.24.3
Adding urllib3 1.24.3 to easy-install.pth file

Using /root/venv/lib/python3.5/site-packages
Searching for requests==2.24.0
Best match: requests 2.24.0
Adding requests 2.24.0 to easy-install.pth file

Using /root/venv/lib/python3.5/site-packages
Searching for certifi==2020.6.20
Best match: certifi 2020.6.20
Adding certifi 2020.6.20 to easy-install.pth file

Using /root/venv/lib/python3.5/site-packages
Searching for chardet==3.0.4
Best match: chardet 3.0.4
Adding chardet 3.0.4 to easy-install.pth file
Installing chardetect script to /root/venv/bin

Using /root/venv/lib/python3.5/site-packages
Searching for idna==2.10
Best match: idna 2.10
Adding idna 2.10 to easy-install.pth file

Using /root/venv/lib/python3.5/site-packages
Finished processing dependencies for python-synology==0.8.2

#### Use
(venv) root@beaglebone:~/python-synology# python
Python 3.5.3 (default, Sep 27 2018, 17:25:39)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from synology_dsm import SynologyDSM
>>> api = SynologyDSM("192.168.0.11", "5000", "myuser", "mypass")
>>> api.login()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/python-synology/synology_dsm/synology_dsm.py", line 159, in login
    raise switcher.get(result["error"]["code"], SynologyDSMLoginFailedException)
TypeError: __init__() missing 2 required positional arguments: 'api' and 'code'

#### Info
DSM 6.2.3-25426 Update 2

**Comment by Gestas** [comment]
@Nitesedge it looks like you are on an ARM device, is that right?

I can't repro this on a x86 with Ubuntu 19 - 

```
user@acomputer:~$ mkvirtualenv -p /usr/local/bin/python3.5 syno64
Running virtualenv with interpreter /usr/local/bin/python3.5
Using base prefix '/usr/local'
...
(syno64) user@acomputer:~$ git clone https://github.com/ProtoThis/python-synology.git
Cloning into 'python-synology'...
...
(syno64) user@acomputer:~/python-synology$ python setup.py install
...
Finished processing dependencies for python-synology==0.8.2

(syno64) user@acomputer:~/python-synology$ python
Python 3.5.3 (default, Aug 10 2020, 09:10:45) 
[GCC 9.2.1 20191008] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from synology_dsm import SynologyDSM
>>> api = SynologyDSM("asyno", "aport", "user", "apassword")
>>> api.login()
True
>>> 
```
I have a Raspberry Pi I can try on, what OS are you running? In the meantime please turn debug mode on and try again, send the results - 
```
api = SynologyDSM("192.168.0.11", "5000", "myuser", "mypass", debugmode=True)
```

**Comment by Quentame** [comment]
Thanks.

try replacing l159 with `raise switcher.get(result["error"]["code"], SynologyDSMLoginFailedException(API_AUTH, result["error"]["code"]))`.

Will submit a fix.
